import math
print(math.pi)
print(math.floor(4.55))
print(math.ceil(4.55))
print(math.degrees(4))
print(math.fabs(44))
print(math.factorial(5))
print(math.sin(3))
print(math.cos(3))
print(math.tan(3))
print(math.log(5))
print(math.log10(5))
print(math.pow(4,3))
print(math.sqrt(100))